version: '3.3'
services:
  zookeeper:
      image: wurstmeister/zookeeper
      container_name: "zk"
  #    ports:
  #      - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      container_name: "kafka"
      depends_on:
      - zookeeper
  #    ports:
  #      - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zk:2181
        KAFKA_CREATE_TOPICS: "payara-kafka-mdb-topic:3:1"
      links:
      - zookeeper:zk
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: dreamit/kafka-mdb
    container_name: "app"
    depends_on:
    - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC_NAME=payara-kafka-mdb-topic

    ports:
        - "8180:8080"
    links:
      - kafka:kafka